### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by aivanovski** [shadaj/create-react-scala-app.g8#22]
Hi,

I'm following the *Quick Overview* section on README.md and can't compile it. Maybe you can fix it, thanks.
```
sbt new shadaj/create-react-scala-app.g8
...
cd ..
sbt dev
```

```
$ sbt dev
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by sbt.TrapExit$ (file:/Users/aleksey/.sbt/boot/scala-2.12.14/org.scala-sbt/sbt/1.5.4/run_2.12-1.5.4.jar)
WARNING: Please consider reporting this to the maintainers of sbt.TrapExit$
WARNING: System::setSecurityManager will be removed in a future release
[info] welcome to sbt 1.5.4 (Azul Systems, Inc. Java 17.0.10)
[info] loading settings for project slinky-playground-build from plugins.sbt ...
[info] loading project definition from /Users/aleksey/tmp/slinky-playground/project
[info] loading settings for project slinky-playground from build.sbt ...
[info] set current project to slinky-playground (in build file:/Users/aleksey/tmp/slinky-playground/)
[warn] sbt 0.13 shell syntax is deprecated; use slash syntax instead: Compile / fastOptJS / startWebpackDevServer
[info] compiling 2 Scala sources to /Users/aleksey/tmp/slinky-playground/target/scala-2.13/classes ...
[info] Updating NPM dependencies
[info] Fast optimizing /Users/aleksey/tmp/slinky-playground/target/scala-2.13/slinky-playground-fastopt
[error] npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
[error] npm warn deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
[error] npm warn deprecated move-concurrently@1.0.1: This package is no longer supported.
[error] npm warn deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
[error] npm warn deprecated figgy-pudding@3.5.2: This module is no longer supported.
[error] npm warn deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
[error] npm warn deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
[error] npm warn deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
[error] npm warn deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
[error] npm warn deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
[error] npm warn deprecated copy-concurrently@1.0.5: This package is no longer supported.
[error] npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
[error] npm warn deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
[error] npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
[error] npm warn deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
[error] npm warn deprecated fs-write-stream-atomic@1.0.10: This package is no longer supported.
[error] npm warn deprecated fsevents@1.2.13: The v1 package contains DANGEROUS / INSECURE binaries. Upgrade to safe fsevents v2
[error] npm warn deprecated fsevents@1.2.13: The v1 package contains DANGEROUS / INSECURE binaries. Upgrade to safe fsevents v2
[error] npm warn deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
[error] npm warn deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
[error] npm warn deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[info] added 847 packages, and audited 848 packages in 12s
[info] 100 packages are looking for funding
[info]   run `npm fund` for details
[info] 26 vulnerabilities (1 low, 2 moderate, 21 high, 2 critical)
[info] To address all issues (including breaking changes), run:
[info]   npm audit fix --force
[info] Run `npm audit` for details.
[info] Writing module entry point for slinky-playground-fastopt-entrypoint.js
[info] Building webpack library bundles for slinky-playground-fastopt in /Users/aleksey/tmp/slinky-playground/target/streams/_global/_global/_global/streams/fastOptJS-webpack-libraries
[info] Writing scalajs.webpack.config.js
[error] node:internal/crypto/hash:79
[error]   this[kHandle] = new _Hash(algorithm, xofLen, algorithmId, getHashCache());
[error]                   ^
[error] Error: error:0308010C:digital envelope routines::unsupported
[error]     at Hash (node:internal/crypto/hash:79:19)
[error]     at Object.createHash (node:crypto:139:10)
[error]     at module.exports (/Users/aleksey/tmp/slinky-playground/target/scala-2.13/scalajs-bundler/main/node_modules/webpack/lib/util/createHash.js:135:53)
[error]     at NormalModule._initBuildHash (/Users/aleksey/tmp/slinky-playground/target/scala-2.13/scalajs-bundler/main/node_modules/webpack/lib/NormalModule.js:417:16)
[error]     at handleParseError (/Users/aleksey/tmp/slinky-playground/target/scala-2.13/scalajs-bundler/main/node_modules/webpack/lib/NormalModule.js:471:10)
[error]     at /Users/aleksey/tmp/slinky-playground/target/scala-2.13/scalajs-bundler/main/node_modules/webpack/lib/NormalModule.js:503:5
[error]     at /Users/aleksey/tmp/slinky-playground/target/scala-2.13/scalajs-bundler/main/node_modules/webpack/lib/NormalModule.js:358:12
[error]     at /Users/aleksey/tmp/slinky-playground/target/scala-2.13/scalajs-bundler/main/node_modules/loader-runner/lib/LoaderRunner.js:373:3
[error]     at iterateNormalLoaders (/Users/aleksey/tmp/slinky-playground/target/scala-2.13/scalajs-bundler/main/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
[error]     at Array.<anonymous> (/Users/aleksey/tmp/slinky-playground/target/scala-2.13/scalajs-bundler/main/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
[error]     at Storage.finished (/Users/aleksey/tmp/slinky-playground/target/scala-2.13/scalajs-bundler/main/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
[error]     at /Users/aleksey/tmp/slinky-playground/target/scala-2.13/scalajs-bundler/main/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
[error]     at /Users/aleksey/tmp/slinky-playground/target/scala-2.13/scalajs-bundler/main/node_modules/graceful-fs/graceful-fs.js:123:16
[error]     at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3) {
[error]   opensslErrorStack: [
[error]     'error:03000086:digital envelope routines::initialization error',
[error]     'error:0308010C:digital envelope routines::unsupported'
[error]   ],
[error]   library: 'digital envelope routines',
[error]   reason: 'unsupported',
[error]   code: 'ERR_OSSL_EVP_UNSUPPORTED'
[error] }
[error] Node.js v22.2.0
[error] Failure on parsing the output of webpack: No content to map due to end-of-input
[error]  at [Source: java.lang.ProcessImpl$ProcessPipeInputStream@4a38a7d5; line: 1, column: 0]
[error] You can try to manually execute the command
[error] node /Users/aleksey/tmp/slinky-playground/target/scala-2.13/scalajs-bundler/main/node_modules/webpack/bin/webpack --bail --profile --json --config /Users/aleksey/tmp/slinky-playground/target/scala-2.13/scalajs-bundler/main/webpack-fastopt.config.js
[error]
[error] java.lang.RuntimeException: Non-zero exit code: 1
[error]         at scala.sys.package$.error(package.scala:30)
[error]         at scalajsbundler.Webpack$.$anonfun$run$2(Webpack.scala:295)
[error]         at scala.util.Either.fold(Either.scala:192)
[error]         at scalajsbundler.Webpack$.run(Webpack.scala:295)
[error]         at scalajsbundler.Webpack$.bundleLibraries(Webpack.scala:239)
[error]         at scalajsbundler.sbtplugin.LibraryTasks$.$anonfun$bundle$2(LibraryTasks.scala:74)
[error]         at sbt.util.FileFunction$.$anonfun$cached$1(FileFunction.scala:80)
[error]         at sbt.util.FileFunction$.$anonfun$cached$4(FileFunction.scala:153)
[error]         at sbt.util.Difference.apply(Tracked.scala:414)
[error]         at sbt.util.Difference.apply(Tracked.scala:394)
[error]         at sbt.util.FileFunction$.$anonfun$cached$3(FileFunction.scala:149)
[error]         at sbt.util.Difference.apply(Tracked.scala:414)
[error]         at sbt.util.Difference.apply(Tracked.scala:389)
[error]         at sbt.util.FileFunction$.$anonfun$cached$2(FileFunction.scala:148)
[error]         at scalajsbundler.sbtplugin.LibraryTasks$.$anonfun$bundle$1(LibraryTasks.scala:77)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error]         at java.base/java.lang.Thread.run(Thread.java:840)
[error] (Compile / fastOptJS / webpack) Non-zero exit code: 1
[error] Total time: 13 s, completed Jul 9, 2024, 4:58:09 PM
```

**Comment by WojciechKuz** [comment]
Hi! I had the same issue, but I was able to resolve it. Though, I ran into the next issue - problem with webpack.
You just need to change the versions of your packages in _build.sbt_. I just searched online for these packages, copied and pasted the latest versions of them into _build.sbt_.
This is part of my _build.sbt_ containing version numbers:
```
scalaVersion := "2.13.15" // "2.13.6"

Compile / npmDependencies += "react" -> "18.3.1"
Compile / npmDependencies += "react-dom" -> "18.3.1"
Compile / npmDependencies += "react-proxy" -> "1.1.8"

Compile / npmDevDependencies += "file-loader" -> "6.2.0"
Compile / npmDevDependencies += "style-loader" -> "4.0.0"
Compile / npmDevDependencies += "css-loader" -> "7.1.2"
Compile / npmDevDependencies += "html-webpack-plugin" -> "5.6.3"
Compile / npmDevDependencies += "copy-webpack-plugin" -> "12.0.2"
Compile / npmDevDependencies += "webpack-merge" -> "6.0.1"

libraryDependencies += "me.shadaj" %%% "slinky-web" % "0.7.4"
libraryDependencies += "me.shadaj" %%% "slinky-hot" % "0.7.4"

libraryDependencies += "org.scalatest" %%% "scalatest" % "3.2.19" % Test

scalacOptions += "-Ymacro-annotations"

webpack / version := "5.97.0" // "4.44.2" "4.47.0" "5.88.2"
startWebpackDevServer / version := "5.1.0" // "3.11.2" "4.15.1"
```

Also, I had to change version of `sbt-scalajs-bundler` in _plugins.sbt_ to `0.21.1`
